name: project_logger
description: An application that tracks and logs work done in general, or with a specific project or client for record-keeping and billing purposes
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  timer_builder: ^1.3.0
  sqflite: ^1.1.7+1
  path_provider: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
   - family: JosefinSans
     fonts:
       - asset: assets/fonts/JosefinSans-Regular.ttf
       - asset: assets/fonts/JosefinSans-Light.ttf
         weight: 300
       - asset: assets/fonts/JosefinSans-Bold.ttf
         weight: 700
   - family: LibreFranklin
     fonts:
       - asset: assets/fonts/LibreFranklin-Regular.ttf
       - asset: assets/fonts/LibreFranklin-Light.ttf
         weight: 300
       - asset: assets/fonts/LibreFranklin-Bold.ttf
         weight: 700