name: project_tracker
description: A useful task / project tracking application, built with Flutter. Create tasks, and use the built-in stopwatch to track how much time you spend on each task. Remember your previous progress, create individual sprints, and get graphical feedback on your average sprint times, break times, and more.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0
  cupertino_icons: ^0.1.2
  timer_builder: ^1.3.0
  sqflite: ^1.2.0
  provider: ^3.2.0
  google_fonts: ^0.2.0
  charts_flutter: ^0.8.1
  path_provider: ^1.5.1
  url_launcher: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

#  fonts:
#   - family: JosefinSans
#     fonts:
#       - asset: assets/fonts/JosefinSans-Regular.ttf
#       - asset: assets/fonts/JosefinSans-Light.ttf
#         weight: 300
#       - asset: assets/fonts/JosefinSans-Bold.ttf
#         weight: 700
#   - family: LibreFranklin
#     fonts:
#       - asset: assets/fonts/LibreFranklin-Regular.ttf
#       - asset: assets/fonts/LibreFranklin-Light.ttf
#         weight: 300
#       - asset: assets/fonts/LibreFranklin-Bold.ttf
#         weight: 700